### ISSUE TITLE
How to inference a single image with given model?

### ISSUE THREAD

**Issue by LLsmile** [facebookresearch/vq2d_cvpr#4]

**Comment by frostinassiky** [comment]
Hi @LLsmile, thanks for the quesiton. Although the whole pipeline is designed to query from videos, you can also inference a single image. Please take a look at function [perform_retrieval](https://github.com/facebookresearch/vq2d_cvpr/blob/9e1e340061347f5dedd811cd2b2331dc0c67ab71/vq2d/baselines/feature_retrieval.py#L16), where you may set `clip_frames` as a one-element list.

An example of calling this function can be found [here](https://github.com/facebookresearch/vq2d_cvpr/blob/9e1e340061347f5dedd811cd2b2331dc0c67ab71/evaluate_vq2d_one_query.py#L106).
